#~/.config/starship.toml

add_newline = true  # Inserts a blank line between shell prompts
command_timeout = 1000  # Change command timeout from 500 to 1000 ms
format = """\
$env_var\
$hostname\
$all"""  # Add custom formatting before other stuff

# Drop ugly default prompt characters
[character]
success_symbol = '[➜](bold green) '
error_symbol = '[➜](bold red) '

# ---

# Shows the current username
[env_var.USER]
format = '[ $env_value](bold green)'
variable = "USER"
disabled = false

# Shows the hostname
[hostname]
ssh_only = false
format = "[@$hostname](bold green) "
disabled = false

# Shows current directory
[directory]
truncation_length = 1
truncation_symbol = "…/"
home_symbol = " ~"
read_only_style = "197"
read_only = "  "
format = "at [$path]($style)[$read_only]($read_only_style) "

# Shows current git branch
[git_branch]
symbol = " "
format = "branch [$symbol$branch]($style) "
# truncation_length = 4
truncation_symbol = "…/"
style = "bold green"

# Shows current git status
[git_status]
format = '[\($all_status$ahead_behind\)]($style) '
style = "bold green"
conflicted = "󰮛 "
up_to_date = " "
untracked = " "
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"
stashed = "󰏖 "
modified = " "
staged = '[++\($count\)](green)'
renamed = " "
deleted = "󰩹 "

# Shows kubernetes context and namespace
[kubernetes]
format = '[$symbol$context](bold purple) '
disabled = false

[container]
disabled = true

# ---
